version: "3.7"
services:
  backend:
    container_name: server 
    build:
      context: server  
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
    ports: ['3000:3000']
    networks:
      - backend
      - frontend

  frontend:
    container_name: client
    build:
      context: client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - '8081:80'
    # environment:
    #     - NGINX_HTTP_PORT_NUMBER=8080
    networks:
      - frontend

networks:
  backend:
  frontend:
